### ISSUE TITLE
Mismatch problem occurred while training the network

### ISSUE THREAD

**Issue by Mariclen** [daodaofr/AlignPS#6]
**Hello, I want to reimplement the experiment, however, when I started training AlignPS (on CUHK), I encountered the following problems. No errors were reported, but the network is not training.**
''''''''
2021-04-11 00:00:02,350 - mmdet - INFO - load model from: open-mmlab://detectron2/resnet50_caffe
2021-04-11 00:00:02,719 - mmdet - WARNING - The model and loaded state dict do not match exactly

unexpected key in source state_dict: conv1.bias

2021-04-11 00:00:08,895 - mmdet - INFO - Start running, host: xxxxx, work_dir: /home/xxxxx/AlignPS/work_dirs/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_focal_x4_bg-2_lconv3dcn_sub_triqueue_dcn0
2021-04-11 00:00:08,908 - mmdet - INFO - workflow: [('train', 1)], max: 24 epochs
'''''''''

**I completely followed the steps in install.md to configure the environment, and my conda list is as follows(python3.6.13 + pytorch1.4.0 + mmdet2.4.0 + mmcv-full1.1.5):**
_libgcc_mutex             0.1                        main    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
addict                    2.4.0                    pypi_0    pypi
blas                      1.0                         mkl    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
ca-certificates           2021.1.19            h06a4308_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
certifi                   2020.12.5        py36h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
cudatoolkit               10.1.243             h6bb024c_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
cycler                    0.10.0                   pypi_0    pypi
cython                    0.29.22                  pypi_0    pypi
freetype                  2.10.4               h5ab3b9f_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
intel-openmp              2020.2                      254    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
jpeg                      9b                   h024ee3a_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
kiwisolver                1.3.1                    pypi_0    pypi
lcms2                     2.12                 h3be6417_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
ld_impl_linux-64          2.33.1               h53a641e_7    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libffi                    3.3                  he6710b0_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libgcc-ng                 9.1.0                hdf63c60_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libgfortran-ng            7.3.0                hdf63c60_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libpng                    1.6.37               hbc83047_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libstdcxx-ng              9.1.0                hdf63c60_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libtiff                   4.1.0                h2733197_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
lz4-c                     1.9.3                h2531618_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
matplotlib                3.3.4                    pypi_0    pypi
mkl                       2020.2                      256    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
mkl-service               2.3.0            py36he8ac12f_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
mkl_fft                   1.3.0            py36h54f3939_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
mkl_random                1.1.1            py36h0573a6f_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
mmcv-full                 1.1.5                    pypi_0    pypi
mmdet                     2.4.0                     dev_0    <develop>
mmpycocotools             12.0.3                   pypi_0    pypi
ncurses                   6.2                  he6710b0_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
ninja                     1.10.2           py36hff7bd54_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
numpy                     1.19.2           py36h54aff64_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
numpy-base                1.19.2           py36hfa32c7d_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
olefile                   0.46                     py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
opencv-python             4.5.1.48                 pypi_0    pypi
openssl                   1.1.1k               h27cfd23_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
pillow                    8.2.0            py36he98fc37_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
pip                       21.0.1           py36h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
pyparsing                 2.4.7                    pypi_0    pypi
python                    3.6.13               hdb3f193_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
python-dateutil           2.8.1                    pypi_0    pypi
pytorch                   1.4.0           py3.6_cuda10.1.243_cudnn7.6.3_0    pytorch
pyyaml                    5.4.1                    pypi_0    pypi
readline                  8.1                  h27cfd23_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
scipy                     1.5.2            py36h0b6359f_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
setuptools                52.0.0           py36h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
six                       1.15.0           py36h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
sqlite                    3.35.4               hdfb4753_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
terminaltables            3.1.0                    pypi_0    pypi
tk                        8.6.10               hbc83047_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
torchvision               0.5.0                py36_cu101    pytorch
wheel                     0.36.2             pyhd3eb1b0_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
xz                        5.2.5                h7b6447c_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
yapf                      0.31.0                   pypi_0    pypi
zlib                      1.2.11               h7b6447c_3    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
zstd                      1.4.9                haebb681_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main

**I checked ISSUES in open-mmlab/mmdetection, someone said:**
"This is not an error. It is normal when using the resnet pre-trained model as the conv1.bais has been absorbed in the conv1.weight."
**But my network cannot continue training. Could you give me some guidance? Thank you!**

**Environment**
sys.platform: linux
Python: 3.6.13 |Anaconda, Inc.| (default, Feb 23 2021, 21:15:04) [GCC 7.3.0]
CUDA available: True
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 10.1, V10.1.243
GPU 0,1,2,3: Tesla P100-PCIE-16GB
GCC: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
PyTorch: 1.4.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

TorchVision: 0.5.0
OpenCV: 4.5.1
MMCV: 1.1.5
MMDetection: 2.4.0+c20cf32
MMDetection Compiler: GCC 7.3
MMDetection CUDA Compiler: 10.1

**Comment by daodaofr** [comment]
I think it's okay, you just need to wait until the network starts training.

**Comment by Mariclen** [comment]
Haha, the whole night passed yesterday, the train log is still like this, stoping at "mmdet - INFO - workflow: [('train', 1)], max: 24 epochs". It has only occupied 805M of GPU memory(you said it needs about 4G memory on GPU in another issue). Have you modified the parameter structure of resnet_caffe.pth?

**Comment by daodaofr** [comment]
I didn't modify it. Could you try pytorch=1.7.0?

**Comment by daodaofr** [comment]
After loading the network, the model will load the images and annotations. So you may check whether the path of the image and the annotations are configured in the right way.

Here is my log:

2021-03-31 11:27:10,912 - mmdet - INFO - load model from: open-mmlab://detectron2/resnet50_caffe
2021-03-31 11:27:11,860 - mmdet - WARNING - The model and loaded state dict do not match exactly

unexpected key in source state_dict: conv1.bias

2021-03-31 11:27:19,082 - mmdet - INFO - Start running, host: xxxx, work_dir: xxxxx/AlignPS/work_dirs/prw_base_focal_labelnorm_sub_ldcn_fg15_wd1-3
2021-03-31 11:27:19,185 - mmdet - INFO - workflow: [('train', 1)], max: 24 epochs
loading annotations into memory...
Done (t=0.18s)
creating index...
index created!

**Comment by Mariclen** [comment]
**Thanks for your reply! I tried python3.8.8+pytorch1.7.0 today. But the network was still not training and I don't know why. =.=||**

**The training log is shown below.**
/home/xxxxx/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/cnn/bricks/conv_module.py:100: UserWarning: ConvModule has norm and bias at the same time
  warnings.warn('ConvModule has norm and bias at the same time')
2021-04-12 16:58:01,343 - mmdet - INFO - load model from: open-mmlab://detectron2/resnet50_caffe
2021-04-12 16:58:02,309 - mmdet - WARNING - The model and loaded state dict do not match exactly

unexpected key in source state_dict: conv1.bias

2021-04-12 16:58:12,527 - mmdet - INFO - Start running, host: xxxxx, work_dir: /home/xxxxx/AlignPS/work_dirs/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_focal_x4_bg-2_lconv3dcn_sub_triqueue_dcn0
2021-04-12 16:58:12,527 - mmdet - INFO - workflow: [('train', 1)], max: 24 epochs
loading annotations into memory...
Done (t=0.54s)
creating index...
index created!

**It seems the model and annotations are already loaded and I don't know where it stopped.**

**Comment by daodaofr** [comment]
It's difficult for me to identify this issue because it doesn't happen in my case. 

My suggestion is that you could try a standard dataset and model to verify whether MMDetection works fine on your machine (https://mmdetection.readthedocs.io/en/latest/1_exist_data_model.html#train-predefined-models-on-standard-datasets).

Otherwise, you could print some messages to find where the code stops.

**Comment by Mariclen** [comment]
When I changed a server, the problem was solved. Thanks for your help!
